### PR TITLE
noir_bignum 0.4.0 support

### PR DESCRIPTION
**Pull request by jp4g**
# Description

## Problem\*

Updates to noir-bignum 0.4.0

## Summary\*

Updates to use the new noir-bignum api in 0.4.0

Tested to work with 2048 bit keygen so it is 90% of the way done

## Additional Context

Todo still:
 1. I cannot get the 1024 bit tests working for some reason - gives
 ```
 error: Failed to solve program: 'Failed to solve brillig function'
   ┌─ /home/user/nargo/github.com/noir-lang/noir-bignumv0.4.0/src/utils/split_bits.nr:86:16
   │
86 │         assert(hi == 0);
```
2. I have not updated the readme
3. I have not updated the signature gen rust crate to match the new input api

# PR Checklist\*

- [x] I have tested the changes locally.
- [x] I have formatted the changes with [Prettier](https://prettier.io/) and/or `cargo fmt` on default settings.

### CODE REVIEW

**Comment by jp4g** [comment]
Also compilation of example on 0.37.0 gives

```
The application panicked (crashed).
Message:  assertion failed: i < b
Location: /home/runner/work/noir/noir/acvm-repo/acvm/src/compiler/optimizers/merge_expressions.rs:75
```
from the `rsa.verify_sha256_pkcs1v15(hash, bn,65537)` line which I have no clue how to address

**Comment by iAmMichaelConnor** [comment]
Thanks @jp4g, we're working to understand why the 1024-bit test failed. It looks to be a problem with release 0.3.7 of bignum. We'll let you know what we find.

**Comment by iAmMichaelConnor** [comment]
We've also found the same bug relating to updating to Noir 0.37.0, thanks again! We're investigating that too :)

**Comment by TomAFrench** [comment]
Thanks for this. We've updated this library to use the new bignum library in #30 so I'm going to close this PR.

**Pull request closed without merging**
