### PR TITLE
feat!: update to noir-bignum v0.4.1

### PR DESCRIPTION
**Pull request by TomAFrench**
Pulling in #29 as @iammichaelconnor's repo wont allow me to push to it.

### CODE REVIEW

**Comment by TomAFrench** [comment]
@iAmMichaelConnor Looks like the signature generation needs to be updated so that it outputs the new bignum param fields which got added in your refactor.

**Comment by iAmMichaelConnor** [comment]
I think I've updated the `signature_gen/main.rs` file to generate the data?
The aspect of the signature_gen/main.rs file that I didn't touch yet is the functionality to print to toml - is that what you're referring to?
Interestingly, if I check out this branch and run `nargo test` using noir 0.36.0, all tests pass? EDIT: oh no, the example/ dir tests fail because that requires a new Noir release.

**Comment by iAmMichaelConnor** [comment]
Ohhh, it's testing via nargo execute - ok, yeah I'll update the toml code generator.

**Comment by iAmMichaelConnor** [comment]
I changed the `main` function in `examples/` so that the data in the Prover.toml is easier to generate (I don't want to bother generating the u60 versions of the modulus). 
The upshot of that is: this PR is compatible with Noir v0.36.0, so we don't need to wait for a new release of Noir.

The downside is: that pesky bug where `nargo compile` of `examples/` causes a compiler error disappears, lost forever.

**Pull request merged**
